name: liga_master
description: "Proyecto Integrado Liga Master"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  provider: ^6.1.4
  firebase_auth: ^5.5.2
  rxdart: ^0.28.0
  fluttertoast: ^8.2.12
  
  location_picker_flutter_map: ^3.1.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/stringsData/appstrings_en.json
    - assets/stringsData/appstrings_es.json
