name: liga_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.0
  cloud_firestore: ^5.6.0
  provider: ^6.1.4
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
